import React, { Component } from 'react';

const initData = {
    itemImg: "/img/Octopus/Info/introduction.png",
    date: "2022-03-30",
    tab_1: "Description",
    tab_2: "Properties",
    tab_3: "Details",
    ownerImg: "./img/pp-removebg-preview.png",
    itemOwner: "SafeArt",
    created: "?? ?? 2021",
    title: "Octopus",
    content: "What if we told you that the 10000 Octopuses in this collection are 100% made of water? It may sound strange but this is all they are made of and you will see why. The story behind this collection takes a non-linear course, as geeks would say. We may relate it to that time when we are merely staring at the sky, and the clouds cause our minds to wander to new startling thoughts about our lives. Indeed, at the beginning we do not have a clear idea of where our experiments will take us and what the collection will look like. It all started with solving ugly mathematical equations to simulate the movement of water. In other words, we define a domain in which water flows (for example a straight channel) and by solving these equations we are able to know the characteristics of the water flow in every point of the domain over time. Then, as if we were sitting on a rock watching a river flow, we look at the simulation results and we notice that the formations generated by the water pouring into the channel resemble the tentacles of an octopus. This is the point at which our collection starts to have a concrete aspect. It is a little amusing that something related to water emerges by coincidence from the simulation of water. The appearance of an aquatic creature, like the cloudy sky, leads to some deeper considerations and the meaning of Octopus collection. The environment that surrounds us is also our essence, as it is for the Octopuses; we are the world we live in. This is why we should care.",
    price_1: "0.5 ETH",
    count: "1 of 10000",
}

class ItemDetails extends Component {
    state = {
        initData: {},
    }
    componentDidMount(){
        this.setState({
            initData: initData,
        })
    }
    render() {
        return (
            <section className="item-details-area mt-5">
                <div className="container mt-5">
                    <div className="row justify-content-between">
                        <div className="col-md-5 col-xs-12">
                            <div className="item-info">
                                <div className="item-thumb text-center mt-5">
                                    <img src={this.state.initData.itemImg} alt="" />
                                </div>
                            </div>
                        </div>
                        <div className="col-md-7 col-xs-12">
                            {/* Content */}
                            <div className="content mt-5 mt-lg-0">
                                <h1 className="m-0">{this.state.initData.title}</h1>
                                <p className="text-octopus">{this.state.initData.content}</p>
                                {/* Owner */}
                                <div className="owner d-flex align-items-center">
                                    <span>Owned By</span>
                                    <a className="owner-meta d-flex align-items-center ml-3">
                                        <img className="avatar-sm rounded-circle" src={this.state.initData.ownerImg} alt="" />
                                        <h6 className="ml-2">{this.state.initData.itemOwner}</h6>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        );
    }
}

export default ItemDetails;